### ISSUE TITLE
Androidsupport 

### ISSUE THREAD

**Issue by hurradiegams** [karma-works/entgender-y#1]
Ist geplant, das Addon auch für Android zu veröffentlichen?

**Comment by karma-works** [comment]
Aktuell werden keine neuen Plugins für Mozilla für Firefox (Android)
bewilligt. Sobald Mozilla wieder Plugins aufnimmt wird das Plugin auch für
Android erscheinen.Das Plugin ist wahrscheinlich ohne Anpassungen auf
Android lauffähig. Der einzige Umweg besteht momentan in einem Bookmarklet
und ist etwas kompliziert einzurichten, siehe https://gendern.uber.space/

hurradiegams ***@***.***> schrieb am Mo., 20. Sep. 2021,
13:33:

**Comment by hurradiegams** [comment]
Alles klar, danke für die Info und das Addon :)
