### ISSUE TITLE
Please keep your libs up-to-date

### ISSUE THREAD

**Issue by mieseprem** [karma-works/entgender-y#10]
Hi Ihr,

ich habe gerade mal das Repo geklont und erste Schritte gewagt. Typescript ist zugegebenermaßen eine ganz neue Welt für mich....
Das erste was mir aufgefallen ist, ist folgendes:

> ~/git/entgender-y$ npm install
> ...
> 
> added 1880 packages from 1509 contributors and audited 1948 packages in 289.017s
> 
> 81 packages are looking for funding
>   run `npm fund` for details
> 
> found 191 vulnerabilities (7 low, 108 moderate, 76 high)
>   run `npm audit fix` to fix them, or `npm audit` for details

So sehr ich Euer Plugin mag, aber diese Ausgabe in Kombination mit dem letzten Commit im November lässt mich vermuten, dass das Plugin nicht wirklich gepflegt wird.
Das finde ich grundsätzlich verständlich/nachvollziehbar bei privatem Code. Aber diesen dann bitte nicht [zur allgemeinen Verwendung anbieten](https://addons.mozilla.org/de/firefox/addon/entgendy-entgendern-phettberg). Wenn Ihr möchtet, dass Euer Code auf fremden Rechnern läuft, dann müsst Ihr Euch (finde ich) auch der Verantwortung stellen und diesen regelmäßig pflegen. 
Wenn Ihr das nicht könnt oder wollt, oder sich niemand findet der diese Aufgabe wahrnimmt, dann solltet Ihr das Plugin besser zurückziehen.

**Comment by karma-works** [comment]
Salut mieseprem,

Danke für den Hinweis "zur allgemeinen Verwendung". Das Plugin ist jetzt als "experimentell" in den Mozilla Addons markiert und ich habe einen Hinweis bezüglich der Sicherheit und Aktualität im Beschreibungstext aufgenommen. 

Updates für Paket-Updates werde ich hier dokumentieren. Vermutlich kann  ein Grossteil der Dependencies auch entfernt werden, was noch besser wäre.

Übrigens: Open Source lebt von der Mithilfe. Falls Du dich mit JavaScript auskennst, sind Verbesserung gerne willkommen.

**Comment by mieseprem** [comment]
> Open Source lebt von der Mithilfe. Falls Du dich mit JavaScript auskennst, sind Verbesserung gerne willkommen

Leider kenne ich JavaScript/TypeScript überhaupt nicht. Sonst würde ich gerne helfen.
Ich hatte ein wenig auf "Low hanging fruits" gehofft und daher den Code mal geklont. Wenn ich doch etwas beitragen kann, dann bekommst Du einen PR 😋

**Comment by karma-works** [comment]
Die meisten Pakete sind jetzt wieder auf dem aktuellen Stand, schliesse daher dieses Ticket.
6 vulnerabilities (3 low, 3 moderate)
