### ISSUE TITLE
Kann ich mitentwickeln + baut nicht

### ISSUE THREAD

**Issue by chris0385** [karma-works/entgender-y#15]
Hallo, 

ich wollte am plugin entwickeln, es fiel auf, dass `npm run bundle` nicht funktioniert (ENOENT: no such file or directory, open 'entgender-y/dist/manifest.json'), weil `~/.parcelrc` nicht da ist. 
```
{
  "extends": ["@parcel/config-default"],
  "reporters":  ["parcel-reporter-static-files-copy"]
}
```
Die Datei `replacement.test.ts` enthält auch ein Fehler (die Klasse `Replacements` existiert nicht). Wurde vielleicht etwas nicht eingecheckt?

Was ich machen wollte, ist den Addon so erweitern, dass andere entgender-Alternativen auswählbar sind (z.B. https://geschlechtsneutral.net/kurzubersicht-uber-das-gesamtsystem/). Dies würde einiges an Refactoring bedeuten, z.B die Methoden `artikelUndKontraktionen, entferneBinnenIs, entferneDoppelformen, entfernePartizip, ersetzeGefluechteteDurchFluechtlinge` aus der Klasse `BeGone` auslagern, um die Text-Ersetzungs-Logik von der DOM Bearbeitung zu trennen.
Vielleicht kann auch ein Teil konfigurierbar gemacht werden, um die Reguläre Ausdrücke gemeinsam zu halten (falls es sich bietet).

Damit meine Änderungen aber dann im aktuellen Addon übernommen werden kann (wenn du es dann übernehmen willst), sollte ich auf dem aktuellsten Stand arbeiten, um Merge-Konflikte zu vermeiden. Daher wollte ich wissen, ob noch Code-Änderungen existieren, die nicht im main-Branch sind.

**Comment by karma-works** [comment]
Hallo,

Ich fände es sehr begrüssenswert die Änderungen in den Plugin aufzunehmen, insbesondere wird es dadurch einfacher die Dependencies aktuell zu halten. Idealerweise kann man dann zwischen verschiedenen Varianten umschalten.

Auch das von dir angesprochene Refactoring ist sehr zu begrüssen.

Ausser dem .parcelrc sind mir keine fehlenden Dateien aufgefallen. Falls dir noch andere Dateien fehlen oder andere Probleme auftreten bitte einfach wieder melden. :-)
