### ISSUE TITLE
Baden-Baden -> Bady 

### ISSUE THREAD

**Issue by Targunitoth** [karma-works/entgender-y#2]
Hey, cooles Plug-in.
Aus Baden-Baden wird Bady, ist das gewollt?

**Comment by karma-works** [comment]
Nein das ist natürlich nicht gewollt. Danke für die Meldung, das
vereinfacht die Verbesserung des Plugins. Der Fehler wird alsbald
korrigiert.

Targunitoth ***@***.***> schrieb am Di., 21. Sep. 2021, 13:39:

**Comment by karma-works** [comment]
Vielen Dank für das einreichen des Issues! Das Problem ist mit der aktuellen Plugin Version 2021.11.9 behoben.
Die Version ist voraussichtlich heute in Firefox und die kommenden Tage in Chrome und Edge verfügbar.
