### ISSUE TITLE
"Die Corona-Zahlen steigen und steigen" -> "Die Corona-undefinedZahlen steigys"

### ISSUE THREAD

**Issue by hurradiegams** [karma-works/entgender-y#4]
Vielen Dank für das Plugin, oben beschriebener Fehler tritt bei der URL https://www.derstandard.at/story/2000130999348/die-coronazahlen-steigen-und-steigen-letzte-ausfahrt-lockdown auf.

**Comment by karma-works** [comment]
Vielen Dank für das Einreichen des Issues! Das Problem ist mit der aktuellen Plugin Version 2021.11.9 behoben.
Die Version ist voraussichtlich heute in Firefox und die kommenden Tage in Chrome und Edge verfügbar.
