### ISSUE TITLE
Stellvertretende*r Datenschutzbeauftragte*r -> Stellvertretendes Datenschutzbeauftragtes

### ISSUE THREAD

**Issue by Targunitoth** [karma-works/entgender-y#5]
Ich bin mir hier unsicher wie hier die richtige Form ist, aber so klingt es falsch für mich.

Browser: Firefox
Plugin Version: 2021.11.14

Ursprungstext (nicht entgenderter Text): Stellvertretende\*r Datenschutzbeauftragte\*r
Ist-Situation (Ergebnis mit dem Plugin): Stellvertretendes Datenschutzbeauftragtes
Soll-Situation (keine Änderung oder entgendert nach Phettberg): Stellvertretendy Datenschutzbeauftragty oder Stellvertretende Datenschutzbeauftragty

**Comment by karma-works** [comment]
Vielen Dank für ihre Mitwirkung bei der Entwicklung des Plugins. Der Fehler ist nun korrigiert und die neue Version wird in den nächsten Stunden publiziert. Ihr Browser aktualisiert die Version automatisch. Falls Sie ungeduldig sind, können Sie in ihrem Browser unter den Plugin-Einstellungen auch manuell die Version aktualisieren.


Im Plugin ist es jetzt wie folgt implementiert

- Stellvertretendes Datenschutzbeauftragty (Stellvertretende*r ist hier keine Personenbezeichnung und  wird somit mit dem Neutrum konjugiert)

- Stellvertretendy falls Stellvertrende*r alleine steht (=Personenbezeichnung)
